### ISSUE TITLE
Link to blog post and live demo

### ISSUE THREAD

**Issue by jsantell** [google-ar/WebAR-Article#1]
We should link to the [demo](https://google-ar.github.io/WebAR-Article/public/) in the URL of this repo and in the README, as well as the corresponding [blog post](https://www.blog.google/products/google-vr/augmented-reality-web-everyone/)

**Comment by rezaali** [comment]
Thanks for pointing that out @jsantell Updated the README commit: f0bc279904d163b57a71faeb3889667be2ec24fb
